// Generated by CoffeeScript 1.3.3
(function() {
  var appData;

  this.App = angular.module('BlinkApp', ['appData']);

  appData = angular.module('appData', []).factory('Data', function() {
    return alert("Hello");
  });

  this.AppController = function($scope, Data) {};

}).call(this);
