// Generated by CoffeeScript 1.3.3
(function() {

  this.bad = angular.module('badModule', []);

  this.bad.factory('fromBadFactory', function() {
    return {
      sayHello: function(text) {
        return "Hello " + text;
      }
    };
  });

  this.good = angular.module('myApp', ['badModule']);

  this.GoodCtrl = function($scope, fromBadFactory) {
    return $scope.fromBadFactory = fromBadFactory.sayHello('World');
  };

}).call(this);
