// Generated by CoffeeScript 1.3.3
(function() {

  this.bad = angular.module('badModule', []);

  this.bad.factory('Data', function() {
    var sayHello;
    return sayHello = function(text) {
      return "Hello " + text;
    };
  });

  this.app = angular.module('BlinkApp', ['badModule']);

  this.AppController = function($scope, Data) {
    return $scope.hello = Data.sayHello('World');
  };

}).call(this);
